#
# Makefile for the linux accessfs routines.
#

obj-$(CONFIG_ACCESS_FS) += accessfs.o
obj-$(CONFIG_ACCESSFS_USER_CAPABILITIES) += usercaps.o
obj-$(CONFIG_ACCESSFS_USER_PORTS) += userports.o

accessfs-objs := inode.o
usercaps-objs := capabilities.o
userports-objs := ip.o
